#!/bin/bash


  #SCRIPT TO INSTALL DOCKER ON CENTOS SERVER

sudo yum remove docker  docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-engine

sudo yum install -y yum-utils -y

sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo -y

sudo yum install docker-ce docker-ce-cli containerd.io -y

systemctl start docker

systemctl enable docker

systemctl status docker
